"""empty message

Revision ID: 03e161a1770f
Revises: 
Create Date: 2021-11-03 15:56:03.525632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03e161a1770f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airplane',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('total_flight_count', sa.Integer(), nullable=True),
    sa.Column('airline', sa.String(), nullable=True),
    sa.Column('info', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airport_start', sa.String(), nullable=True),
    sa.Column('airport_end', sa.String(), nullable=True),
    sa.Column('airplane_speed', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'ENDED', name='flightstatusenum'), nullable=False),
    sa.Column('airplane_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['airplane_id'], ['airplane.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight')
    op.drop_table('airplane')
    # ### end Alembic commands ###
